version: '3.8'
services:
  jokes-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - redis-server
    links:
      - redis-server
  redis-server:
    image: redis